Repository orange-alliance/toa-react, pull requests merged in 2020-08, with the labels that each got.

#16 Updated Dockerfile
  Dockerfile
Labels: bug, enhancement, good first issue, help wanted, invalid

#18 Fixes server crashing on client connect.
  public/index.js.LICENSE.txt
  public/index.js.map
  server/PageRenderer.tsx
Labels: back-end, bug

#19 Adds server-rendered data pipeline.
  README.md
  client/index.tsx
  public/favicon.png
  public/index.html
  server/PageRenderer.tsx
  server/Server.ts
  shared/index.ts
  shared/stores/Types.ts
Labels: back-end, design, enhancement

#23 i18n Support / Functional Pages
  .babelrc
  .eslintrc.json
  .github/workflows/deploytoAksCluster.yml
  .prettierrc.json
  STYLE.md
  client/App.scss
  client/App.tsx
  client/AppResponsiveDrawer.tsx
  client/AppRoutes.tsx
  client/AppTheme.tsx
  client/components/AnnouncementCard.tsx
  client/components/ListItemLink.tsx
  client/components/SimpleMatchTable.tsx
  client/components/SimpleTeamPaper.tsx
  client/components/StatisticCard.tsx
  client/i18n/index.ts
  client/index.tsx
  client/modules/LeaderboardsModule.tsx
  client/pages/about/AboutPage.tsx
  client/pages/events/EventsPage.tsx
  client/pages/home/HomePage.tsx
  client/pages/index.ts
  client/pages/language/Language.tsx
  client/pages/teams/TeamsPage.tsx
  config/webpack.client.dev.config.js
  config/webpack.client.prod.config.js
  config/webpack.library.config.js
  config/webpack.server.config.js
  images.d.ts
  manifests/deployment.yml
  manifests/service.yml
  nodemon.json
  package-lock.json
  package.json
  public/locales/README.MD
  public/locales/en/translation.json
  public/locales/es/translation.json
  public/locales/he/translation.json
  public/locales/zh/translation.json
  server/Server.ts
  shared/PageData.ts
  shared/PageProperties.ts
  shared/index.ts
  shared/providers/TOAProvider.ts
  shared/stores/Actions.ts
  shared/stores/Reducer.ts
  shared/stores/Types.ts
  tsconfig.json
  tslint.json
Labels: design, enhancement

#24 Fixed things that somehow didn't get merged in.
  .gitignore
  public/index.js.LICENSE.txt
  shared/index.ts
  shared/stores/Types.ts
Labels: URGENT, bug

#27 Added SSR internationalization. App should build/run flawlessly.
  client/AppRoutes.tsx
  client/i18n/index.ts
  client/index.tsx
  client/pages/home/HomePage.tsx
  client/pages/index.ts
  client/pages/language/Language.tsx
  modules.d.ts
  package-lock.json
  package.json
  public/index.html
  public/index.js.LICENSE.txt
  public/index.js.map
  public/locales/en/translation.json
  server/PageRenderer.tsx
  server/Server.ts
Labels: URGENT, bug

#28 Deleted now pointless workflows that fail CI.
  .github/workflows/deploytoAksCluster.yml
Labels: bug

#30 Create docker-build.yml
  .github/workflows/docker-build.yml
Labels: enhancement
